# Base image
FROM resin/raspberry-pi2-python:2.7

RUN mkdir -p /usr/app

WORKDIR /usr/app

ADD requirements.txt ./

RUN pip install -r requirements.txt && rm requirements.txt

ADD littletrain ./

CMD ["python", "-m", "littletrain"]